FROM node:11

RUN set -ex && \
    apt-get -qq update && \
    apt-get -qq -y install bash \
      unzip \
      wget \
      python3 \
      python3-pip \
      software-properties-common

RUN set -ex && \
    pip3 install boto boto3 botocore ansible

RUN npm install yarn -g
