version: "3"

services:
  jenkins:
    container_name: jenkins
    image: local/jenkins:latest
    build: .
    restart: always
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.secret:/run/secrets/jenkins
    ports:
      - "8080:8080"
      - "50000:50000"

volumes:
  jenkins_home:
